import Head from 'next/head'
import Header from '../components/Header.jsx'
import Body from '../components/Body.jsx'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Dex Sim</title>
        <meta name="Dex Sim" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <Body/>
    </div>
  )
}
