import Head from 'next/head'
import Header from '../components/Header.jsx'
import Body from '../components/Body.jsx'
import Topper from '../components/Topper'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Dex Sim</title>
        <meta name="Dex Sim" content="Generated by create next app" />
        <link rel="icon" href="" />
      </Head>
      <Header/>
      <Topper />
      <Body/>
    </div>
  )
}
